import type { Severity, ControlStatus } from '@/lib/db-types';

export interface ProviderControlResult {
  controlId: string;
  status: ControlStatus;
  score: number;
  evidence: string;
  notes: string;
}

export interface ProviderFinding {
  title: string;
  description: string;
  category: string;
  severity: Severity;
  resourceType: string;
  resourceId: string;
  region: string;
  evidence: string;
  businessRisk: string;
  recommendation: string;
}

export interface DataProvider {
  name: string;
  evaluateControl(controlId: string, accountId: string): Promise<ProviderControlResult>;
  scanAccount(accountId: string): Promise<ProviderFinding[]>;
}

export class MockDataProvider implements DataProvider {
  name = 'MockDataProvider';

  async evaluateControl(controlId: string, _accountId: string): Promise<ProviderControlResult> {
    const results: ControlStatus[] = ['PASS', 'FAIL', 'WARNING'];
    const status = results[Math.floor(Math.random() * results.length)];
    return {
      controlId,
      status,
      score: status === 'PASS' ? 100 : status === 'WARNING' ? 50 : 0,
      evidence: `Mock evaluation for control ${controlId}.`,
      notes: 'Generated by MockDataProvider.',
    };
  }

  async scanAccount(_accountId: string): Promise<ProviderFinding[]> {
    return [];
  }
}

export const dataProvider: DataProvider = new MockDataProvider();
