import type {
  ActivityEvent,
  Assessment,
  AuditLogEntry,
  Automation,
  AutomationExecution,
  AwsAccount,
  Control,
  Finding,
  FindingComment,
  HealthCategory,
  HealthTrendPoint,
  Notification,
  Organization,
  Remediation,
  Report,
  User,
} from './types';

export const organization: Organization = {
  id: 'org-1',
  name: 'CloudOps Platform',
  defaultRegion: 'us-east-1',
  defaultEnvironment: 'Production',
};

export const users: User[] = [
  { id: 'u1', name: 'Pawan Kumar', email: 'pawan@cloudops.io', role: 'Super Admin' },
  { id: 'u2', name: 'Sarah Chen', email: 'sarah@cloudops.io', role: 'Platform Admin' },
  { id: 'u3', name: 'Marcus Webb', email: 'marcus@cloudops.io', role: 'DevOps Engineer' },
  { id: 'u4', name: 'Elena Rossi', email: 'elena@cloudops.io', role: 'Security Engineer' },
  { id: 'u5', name: 'David Park', email: 'david@cloudops.io', role: 'Viewer' },
];

export const currentUser = users[0];

export const accounts: AwsAccount[] = [
  {
    id: 'acc-prod',
    name: 'Production',
    accountId: '4827-1933-5566',
    environment: 'Production',
    regions: ['us-east-1', 'us-west-2'],
    healthScore: 86,
    lastAssessment: '2026-08-18T09:30:00Z',
    findingsCount: 12,
    resourcesCount: 1284,
    status: 'Connected',
    owner: 'Sarah Chen',
  },
  {
    id: 'acc-dev',
    name: 'Development',
    accountId: '9102-4471-8823',
    environment: 'Development',
    regions: ['us-east-1'],
    healthScore: 78,
    lastAssessment: '2026-08-17T14:00:00Z',
    findingsCount: 21,
    resourcesCount: 542,
    status: 'Connected',
    owner: 'Marcus Webb',
  },
  {
    id: 'acc-test',
    name: 'Test',
    accountId: '6634-2208-1190',
    environment: 'Test',
    regions: ['us-east-1', 'us-west-2'],
    healthScore: 82,
    lastAssessment: '2026-08-16T11:15:00Z',
    findingsCount: 14,
    resourcesCount: 318,
    status: 'Connected',
    owner: 'Marcus Webb',
  },
];

export const healthCategories: HealthCategory[] = [
  { name: 'Reliability', score: 87 },
  { name: 'Security', score: 91 },
  { name: 'Governance', score: 78 },
  { name: 'Observability', score: 73 },
  { name: 'Backup & DR', score: 69 },
  { name: 'Automation', score: 62 },
];

export const healthTrends: HealthTrendPoint[] = [
  { month: 'Jan', score: 69, reliability: 74, security: 85, governance: 66, observability: 61, backup: 58, automation: 50 },
  { month: 'Feb', score: 71, reliability: 76, security: 86, governance: 68, observability: 63, backup: 60, automation: 53 },
  { month: 'Mar', score: 73, reliability: 78, security: 87, governance: 70, observability: 65, backup: 62, automation: 55 },
  { month: 'Apr', score: 75, reliability: 80, security: 88, governance: 72, observability: 67, backup: 64, automation: 57 },
  { month: 'May', score: 77, reliability: 82, security: 89, governance: 74, observability: 69, backup: 66, automation: 58 },
  { month: 'Jun', score: 78, reliability: 83, security: 90, governance: 75, observability: 70, backup: 67, automation: 59 },
  { month: 'Jul', score: 80, reliability: 85, security: 90, governance: 76, observability: 71, backup: 68, automation: 60 },
  { month: 'Aug', score: 82, reliability: 87, security: 91, governance: 78, observability: 73, backup: 69, automation: 62 },
];

export const riskDistribution = [
  { name: 'Critical', value: 4, severity: 'Critical' as const },
  { name: 'High', value: 12, severity: 'High' as const },
  { name: 'Medium', value: 21, severity: 'Medium' as const },
  { name: 'Low', value: 10, severity: 'Low' as const },
];

export const controls: Control[] = [
  { id: 'SEC-001', name: 'No unrestricted SSH access', category: 'Security', description: 'Security groups must not allow inbound SSH (port 22) from 0.0.0.0/0.', severity: 'High', framework: 'CIS AWS 1.4', status: 'Active' },
  { id: 'SEC-002', name: 'S3 public access blocked', category: 'S3', description: 'S3 buckets must have public access blocked at the account level.', severity: 'Critical', framework: 'CIS AWS 1.3', status: 'Active' },
  { id: 'SEC-003', name: 'CloudTrail enabled', category: 'Security', description: 'AWS CloudTrail must be enabled in all regions for audit logging.', severity: 'High', framework: 'CIS AWS 2.1', status: 'Active' },
  { id: 'IAM-001', name: 'Least privilege IAM', category: 'IAM', description: 'IAM roles and policies must follow least-privilege principles with no wildcard actions.', severity: 'Medium', framework: 'CIS AWS 1.16', status: 'Active' },
  { id: 'EKS-001', name: 'Supported Kubernetes version', category: 'EKS', description: 'EKS clusters must run a Kubernetes version within the vendor-supported window.', severity: 'High', framework: 'EKS Best Practices', status: 'Active' },
  { id: 'EKS-002', name: 'Approved EKS add-ons', category: 'EKS', description: 'EKS add-ons must be aligned to approved versions across environments.', severity: 'High', framework: 'EKS Best Practices', status: 'Active' },
  { id: 'NET-001', name: 'VPC Flow Logs enabled', category: 'Networking', description: 'VPC Flow Logs must be enabled for all production VPCs.', severity: 'Medium', framework: 'AWS Well-Architected', status: 'Active' },
  { id: 'NET-002', name: 'Transit Gateway Flow Logs enabled', category: 'Networking', description: 'Transit Gateway Flow Logs must be enabled for network auditability.', severity: 'Medium', framework: 'AWS Well-Architected', status: 'Active' },
  { id: 'OBS-001', name: 'CloudWatch log retention configured', category: 'Observability', description: 'CloudWatch log groups must have a defined retention policy.', severity: 'Medium', framework: 'AWS Well-Architected', status: 'Active' },
  { id: 'DR-001', name: 'Critical workloads backed up', category: 'Backup', description: 'Critical workloads must have AWS Backup plans configured.', severity: 'High', framework: 'AWS Well-Architected', status: 'Active' },
  { id: 'DR-002', name: 'Backup restore tested', category: 'Backup', description: 'Backup restore procedures must be validated at least quarterly.', severity: 'Critical', framework: 'AWS Well-Architected', status: 'Active' },
  { id: 'GOV-001', name: 'Required resource tags', category: 'Governance', description: 'Resources must carry required tags: owner, environment, cost-center, data-classification.', severity: 'Low', framework: 'Internal Governance', status: 'Active' },
];

function makeComment(id: string, author: string, text: string, daysAgo: number): FindingComment {
  const d = new Date('2026-08-19T10:00:00Z');
  d.setDate(d.getDate() - daysAgo);
  return { id, author, text, createdAt: d.toISOString() };
}

export const findings: Finding[] = [
  // Critical (4)
  {
    id: 'F-1001',
    title: 'Production RDS backup restore has not been validated',
    severity: 'Critical',
    category: 'Backup',
    accountId: 'acc-prod',
    accountName: 'Production',
    environment: 'Production',
    resource: 'db-prod-orders-01',
    owner: 'Sarah Chen',
    status: 'Open',
    dueDate: '2026-08-26',
    createdAt: '2026-08-12T08:00:00Z',
    description: 'The primary production RDS instance has no record of a validated restore test in the last 90 days. Backups are being taken but recovery has never been verified.',
    businessRisk: 'In the event of a data corruption or regional outage, the recovery procedure is unproven and may fail, leading to extended downtime and potential data loss for the orders service.',
    businessImpact: 'Data Risk',
    evidence: 'AWS Backup vault shows daily snapshots for db-prod-orders-01. No restore job found in any account in the last 90 days. Last successful restore test: none on record.',
    recommendation: 'Schedule and execute a full restore test into an isolated VPC, validate application integrity, and document the RTO/RPO. Establish a quarterly restore-test cadence.',
    remediationStage: 'In Progress',
    remediationProgress: 35,
    comments: [
      makeComment('c1', 'Sarah Chen', 'Coordinating with DBA team for a restore window this weekend.', 3),
      makeComment('c2', 'Pawan Kumar', 'This is the top priority for the platform team this sprint.', 1),
    ],
  },
  {
    id: 'F-1002',
    title: 'S3 bucket allows public read access to customer data',
    severity: 'Critical',
    category: 'S3',
    accountId: 'acc-prod',
    accountName: 'Production',
    environment: 'Production',
    resource: 's3-prod-customer-exports',
    owner: 'Elena Rossi',
    status: 'Investigating',
    dueDate: '2026-08-22',
    createdAt: '2026-08-14T12:30:00Z',
    description: 'An S3 bucket containing customer export data has a bucket policy allowing public read access to all objects.',
    businessRisk: 'Sensitive customer data is exposed to the public internet, creating a compliance violation under GDPR and CCPA and a significant data breach risk.',
    businessImpact: 'Data Risk',
    evidence: 'Bucket policy statement: {"Effect":"Allow","Principal":"*","Action":"s3:GetObject","Resource":"arn:aws:s3:::s3-prod-customer-exports/*"}. Public access block settings are not enabled at the account level.',
    recommendation: 'Immediately remove the public read policy statement, enable S3 Block Public Access at the account and bucket level, and audit all objects for prior unauthorized access via CloudTrail.',
    remediationStage: 'In Progress',
    remediationProgress: 60,
    comments: [
      makeComment('c3', 'Elena Rossi', 'Public policy removed. Running CloudTrail analysis to check for access in the last 90 days.', 2),
    ],
  },
  {
    id: 'F-1003',
    title: 'Production EKS control plane running unsupported Kubernetes version',
    severity: 'Critical',
    category: 'EKS',
    accountId: 'acc-prod',
    accountName: 'Production',
    environment: 'Production',
    resource: 'eks-prod-main',
    owner: 'Marcus Webb',
    status: 'Planned',
    dueDate: '2026-09-02',
    createdAt: '2026-08-10T09:00:00Z',
    description: 'The production EKS cluster control plane is running Kubernetes 1.24 which is past end-of-support and no longer receives security patches.',
    businessRisk: 'Running an unsupported Kubernetes version means no security patches for critical CVEs, potential incompatibility with managed add-ons, and loss of AWS support eligibility.',
    businessImpact: 'Security Risk',
    evidence: 'Cluster version: 1.24.17. EKS supported versions: 1.27, 1.28, 1.29, 1.30. Cluster was last upgraded 14 months ago.',
    recommendation: 'Plan a controlled upgrade to 1.29 following the EKS upgrade documentation. Run the upgrade in a maintenance window with rollback procedures documented.',
    remediationStage: 'Planned',
    remediationProgress: 15,
    comments: [
      makeComment('c4', 'Marcus Webb', 'Upgrade window scheduled for Sept 2. Running compatibility tests in staging first.', 4),
    ],
  },
  {
    id: 'F-1004',
    title: 'CloudTrail logging disabled in us-west-2 region',
    severity: 'Critical',
    category: 'Security',
    accountId: 'acc-prod',
    accountName: 'Production',
    environment: 'Production',
    resource: 'CloudTrail (us-west-2)',
    owner: 'Elena Rossi',
    status: 'Open',
    dueDate: '2026-08-21',
    createdAt: '2026-08-15T16:00:00Z',
    description: 'CloudTrail trail is not logging events in the us-west-2 region, creating a blind spot for security auditing and incident response.',
    businessRisk: 'Without complete CloudTrail coverage, security incidents in us-west-2 cannot be investigated, and compliance requirements for audit logging are not met.',
    businessImpact: 'Compliance Risk',
    evidence: 'Trail "management-events" has isMultiRegionTrail=true but logging was disabled for us-west-2 on 2026-07-30. Last log event from us-west-2: 2026-07-30T14:22Z.',
    recommendation: 'Re-enable CloudTrail logging for us-west-2 immediately. Add a CloudWatch alarm to alert on logging disablement. Review who made the change via IAM.',
    remediationStage: 'Backlog',
    remediationProgress: 0,
    comments: [],
  },

  // High (12)
  {
    id: 'F-1005',
    title: 'EKS add-on versions are inconsistent across environments',
    severity: 'High',
    category: 'EKS',
    accountId: 'acc-prod',
    accountName: 'Production',
    environment: 'Production',
    resource: 'eks-prod-main / eks-dev-main / eks-test-main',
    owner: 'Marcus Webb',
    status: 'In Progress',
    dueDate: '2026-09-05',
    createdAt: '2026-08-08T10:00:00Z',
    description: 'EKS add-ons (vpc-cni, kube-proxy, coredns) are running different versions across production, development, and test clusters, leading to inconsistent behavior and deployment risk.',
    businessRisk: 'Inconsistent add-on versions make it difficult to reproduce issues across environments and increase the risk of production failures that cannot be caught in lower environments.',
    businessImpact: 'Operational Risk',
    evidence: 'vpc-cni: prod=v1.12.0, dev=v1.11.3, test=v1.12.0. kube-proxy: prod=v1.24.7, dev=v1.24.7, test=v1.25.3. coredns: all environments differ.',
    recommendation: 'Standardize add-on versions across all clusters. Use GitOps to manage add-on configuration and enforce version parity via CI checks.',
    remediationStage: 'In Progress',
    remediationProgress: 45,
    comments: [],
  },
  {
    id: 'F-1006',
    title: 'Security group allows unrestricted SSH access',
    severity: 'High',
    category: 'Security',
    accountId: 'acc-prod',
    accountName: 'Production',
    environment: 'Production',
    resource: 'sg-prod-web-01',
    owner: 'Elena Rossi',
    status: 'Open',
    dueDate: '2026-09-15',
    createdAt: '2026-08-05T08:00:00Z',
    description: 'Security group permits inbound SSH access from 0.0.0.0/0.',
    businessRisk: 'Internet-exposed SSH increases the attack surface and may allow unauthorized access attempts, brute-force attacks, and potential compromise of production web servers.',
    businessImpact: 'Security Risk',
    evidence: 'Inbound rule: port 22, source 0.0.0.0/0, protocol TCP. Security group is attached to 4 EC2 instances in the production web tier.',
    recommendation: 'Restrict SSH access to approved administrative networks or use AWS Systems Manager Session Manager for secure, audited access without open inbound ports.',
    remediationStage: 'Backlog',
    remediationProgress: 0,
    comments: [
      makeComment('c5', 'Elena Rossi', 'Working with the web team to migrate to Session Manager.', 5),
    ],
  },
  {
    id: 'F-1007',
    title: 'Several critical workloads have insufficient observability',
    severity: 'High',
    category: 'Observability',
    accountId: 'acc-prod',
    accountName: 'Production',
    environment: 'Production',
    resource: 'orders-api, payments-api, inventory-svc',
    owner: 'Sarah Chen',
    status: 'In Progress',
    dueDate: '2026-09-10',
    createdAt: '2026-08-06T11:00:00Z',
    description: 'Three critical microservices lack distributed tracing, custom metrics, and alerting dashboards, making it difficult to detect and diagnose production issues.',
    businessRisk: 'Without proper observability, production incidents take longer to diagnose, increasing MTTR and potentially extending customer-facing outages.',
    businessImpact: 'Availability Risk',
    evidence: 'orders-api: no X-Ray tracing, no custom CloudWatch alarms. payments-api: no dashboard, no SLO defined. inventory-svc: logs present but no metrics.',
    recommendation: 'Instrument all three services with OpenTelemetry, define SLOs and error-rate alerts, and create service-level dashboards in CloudWatch or Grafana.',
    remediationStage: 'In Progress',
    remediationProgress: 30,
    comments: [],
  },
  {
    id: 'F-1008',
    title: 'IAM role with wildcard permissions attached to EC2 instances',
    severity: 'High',
    category: 'IAM',
    accountId: 'acc-prod',
    accountName: 'Production',
    environment: 'Production',
    resource: 'iam-role-ec2-prod-legacy',
    owner: 'Elena Rossi',
    status: 'Investigating',
    dueDate: '2026-09-01',
    createdAt: '2026-08-09T14:00:00Z',
    description: 'An EC2 instance role has an attached policy with Action:* and Resource:*, violating least-privilege principles.',
    businessRisk: 'If any of these instances are compromised, the attacker gains full access to all AWS services in the account, potentially leading to data exfiltration or infrastructure destruction.',
    businessImpact: 'Security Risk',
    evidence: 'Policy "LegacyFullAccess" attached to role "iam-role-ec2-prod-legacy". Policy document: {"Action":"*","Resource":"*"}. Role attached to 2 EC2 instances.',
    recommendation: 'Replace the wildcard policy with a scoped-down policy granting only the permissions the application requires. Use IAM Access Analyzer to identify actual usage.',
    remediationStage: 'Planned',
    remediationProgress: 20,
    comments: [],
  },
  {
    id: 'F-1009',
    title: 'VPC Flow Logs not enabled for production VPC',
    severity: 'High',
    category: 'Networking',
    accountId: 'acc-prod',
    accountName: 'Production',
    environment: 'Production',
    resource: 'vpc-prod-main',
    owner: 'Marcus Webb',
    status: 'Open',
    dueDate: '2026-09-08',
    createdAt: '2026-08-07T09:30:00Z',
    description: 'VPC Flow Logs are not enabled for the primary production VPC, preventing network traffic auditing and security investigation.',
    businessRisk: 'Without flow logs, network-based attacks, misconfigurations, and unauthorized traffic cannot be investigated, hindering incident response and compliance.',
    businessImpact: 'Security Risk',
    evidence: 'VPC vpc-prod-main (vpc-0abc123) has no flow log configurations. VPC contains 6 subnets across 2 AZs hosting production workloads.',
    recommendation: 'Enable VPC Flow Logs to a dedicated S3 bucket with appropriate retention. Configure log format to include all fields for security analysis.',
    remediationStage: 'Backlog',
    remediationProgress: 0,
    comments: [],
  },
  {
    id: 'F-1010',
    title: 'Production RDS instance has no automated backup plan',
    severity: 'High',
    category: 'Backup',
    accountId: 'acc-prod',
    accountName: 'Production',
    environment: 'Production',
    resource: 'db-prod-payments-02',
    owner: 'Sarah Chen',
    status: 'In Progress',
    dueDate: '2026-08-28',
    createdAt: '2026-08-11T13:00:00Z',
    description: 'A production RDS instance handling payments has no AWS Backup plan configured, relying only on default automated backups with no cross-region copy.',
    businessRisk: 'Loss of the payments database without a proper backup plan could result in permanent data loss and inability to process transactions.',
    businessImpact: 'Data Risk',
    evidence: 'RDS instance db-prod-payments-02: BackupRetentionPeriod=7 (default), no AWS Backup plan assigned, no cross-region snapshot copy configured.',
    recommendation: 'Enroll the instance in an AWS Backup plan with daily snapshots, 30-day retention, and cross-region copy to the DR region.',
    remediationStage: 'In Progress',
    remediationProgress: 50,
    comments: [],
  },
  {
    id: 'F-1011',
    title: 'Unused IAM role with excessive permissions detected',
    severity: 'High',
    category: 'IAM',
    accountId: 'acc-dev',
    accountName: 'Development',
    environment: 'Development',
    resource: 'iam-role-dev-deprecated-service',
    owner: 'Marcus Webb',
    status: 'Open',
    dueDate: '2026-09-12',
    createdAt: '2026-08-04T10:00:00Z',
    description: 'An IAM role has not been used in 180 days but retains administrator-level permissions.',
    businessRisk: 'Dormant roles with high privileges are prime targets for privilege escalation attacks if credentials are leaked or compromised.',
    businessImpact: 'Security Risk',
    evidence: 'Role "iam-role-dev-deprecated-service" last used: 2026-02-15. Attached policy: AdministratorAccess. No trust policy updates in 6 months.',
    recommendation: 'Remove the role if no longer needed. If still required, reduce permissions to least-privilege and document the business justification.',
    remediationStage: 'Backlog',
    remediationProgress: 0,
    comments: [],
  },
  {
    id: 'F-1012',
    title: 'EKS node group running deprecated AMI type',
    severity: 'High',
    category: 'EKS',
    accountId: 'acc-dev',
    accountName: 'Development',
    environment: 'Development',
    resource: 'eks-dev-main / nodegroup-dev-1',
    owner: 'Marcus Webb',
    status: 'Planned',
    dueDate: '2026-09-15',
    createdAt: '2026-08-03T11:00:00Z',
    description: 'An EKS managed node group is running on a deprecated Amazon Linux 2 AMI that no longer receives security updates.',
    businessRisk: 'Nodes running deprecated AMIs are vulnerable to known security issues and may become incompatible with future EKS versions.',
    businessImpact: 'Security Risk',
    evidence: 'Node group nodegroup-dev-1: AMI type AL2_x86_64, release version 1.24.17-20240301. Amazon Linux 2 EOL: 2025-06-30.',
    recommendation: 'Upgrade the node group to Amazon Linux 2023 or Bottlerocket. Use a rolling update strategy to minimize disruption.',
    remediationStage: 'Planned',
    remediationProgress: 10,
    comments: [],
  },
  {
    id: 'F-1013',
    title: 'Production workload lacks required resource tags',
    severity: 'High',
    category: 'Governance',
    accountId: 'acc-prod',
    accountName: 'Production',
    environment: 'Production',
    resource: '14 EC2 instances, 3 RDS instances, 7 S3 buckets',
    owner: 'Sarah Chen',
    status: 'In Progress',
    dueDate: '2026-09-20',
    createdAt: '2026-08-02T08:00:00Z',
    description: 'Multiple production resources are missing required tags (owner, environment, cost-center, data-classification), preventing cost allocation and governance.',
    businessRisk: 'Without proper tagging, cost allocation is inaccurate, ownership is unclear, and automated governance policies cannot be enforced.',
    businessImpact: 'Operational Risk',
    evidence: '24 resources missing "owner" tag, 18 missing "cost-center", 14 missing "data-classification". Tag compliance: 61%.',
    recommendation: 'Apply required tags to all resources. Implement tag policies via AWS Organizations and use auto-tagging Lambda for new resources.',
    remediationStage: 'In Progress',
    remediationProgress: 40,
    comments: [],
  },
  {
    id: 'F-1014',
    title: 'CloudWatch log group has no retention policy',
    severity: 'High',
    category: 'Observability',
    accountId: 'acc-prod',
    accountName: 'Production',
    environment: 'Production',
    resource: '/aws/lambda/prod-order-processor',
    owner: 'Sarah Chen',
    status: 'Open',
    dueDate: '2026-09-06',
    createdAt: '2026-08-06T15:00:00Z',
    description: 'A high-volume CloudWatch log group has no retention policy set, causing unbounded log storage growth and cost.',
    businessRisk: 'Unbounded log retention leads to escalating costs and makes log analysis slower and more expensive over time.',
    businessImpact: 'Financial Risk',
    evidence: 'Log group /aws/lambda/prod-order-processor: retention=Never (NeverExpire). Storage: 847 GB and growing. Monthly cost: $423.',
    recommendation: 'Set a 90-day retention policy. Archive logs older than 90 days to S3 with Glacier transition for long-term compliance retention.',
    remediationStage: 'Backlog',
    remediationProgress: 0,
    comments: [],
  },
  {
    id: 'F-1015',
    title: 'Transit Gateway has no flow logs enabled',
    severity: 'High',
    category: 'Networking',
    accountId: 'acc-prod',
    accountName: 'Production',
    environment: 'Production',
    resource: 'tgw-prod-main',
    owner: 'Marcus Webb',
    status: 'Open',
    dueDate: '2026-09-11',
    createdAt: '2026-08-05T09:00:00Z',
    description: 'The production Transit Gateway routing traffic between VPCs and on-premises has no flow logs enabled.',
    businessRisk: 'Inter-VPC and hybrid network traffic cannot be audited, making it difficult to diagnose routing issues or detect suspicious cross-network access.',
    businessImpact: 'Security Risk',
    evidence: 'TGW tgw-prod-main: 0 flow log configurations. TGW has 6 attachments (4 VPC, 2 VPN).',
    recommendation: 'Enable Transit Gateway Flow Logs to a dedicated S3 bucket with 1-year retention for network audit and security analysis.',
    remediationStage: 'Backlog',
    remediationProgress: 0,
    comments: [],
  },
  {
    id: 'F-1016',
    title: 'EKS cluster has no pod-level resource requests configured',
    severity: 'High',
    category: 'EKS',
    accountId: 'acc-dev',
    accountName: 'Development',
    environment: 'Development',
    resource: 'eks-dev-main / 23 deployments',
    owner: 'Marcus Webb',
    status: 'Planned',
    dueDate: '2026-09-18',
    createdAt: '2026-08-01T10:00:00Z',
    description: 'Multiple deployments in the development EKS cluster have no CPU or memory resource requests defined, leading to scheduling instability.',
    businessRisk: 'Without resource requests, the scheduler cannot make informed placement decisions, leading to node starvation and unpredictable pod evictions.',
    businessImpact: 'Availability Risk',
    evidence: '23 of 67 deployments have no resource requests. 41 deployments have no resource limits. Cluster shows frequent pod evictions due to memory pressure.',
    recommendation: 'Define resource requests and limits for all workloads. Use Vertical Pod Autoscaler in recommendation mode to right-size based on actual usage.',
    remediationStage: 'Planned',
    remediationProgress: 15,
    comments: [],
  },

  // Medium (16)
  {
    id: 'F-1017',
    title: 'Multiple CloudWatch log groups have no retention policy',
    severity: 'Medium',
    category: 'Observability',
    accountId: 'acc-dev',
    accountName: 'Development',
    environment: 'Development',
    resource: '12 CloudWatch log groups',
    owner: 'Marcus Webb',
    status: 'Open',
    dueDate: '2026-09-25',
    createdAt: '2026-08-03T14:00:00Z',
    description: 'Twelve CloudWatch log groups in the development account have no retention policy, leading to unbounded storage growth.',
    businessRisk: 'Unbounded log retention causes unnecessary storage costs and slower log queries over time.',
    businessImpact: 'Financial Risk',
    evidence: '12 log groups with retention=NeverExpire. Total storage: 312 GB. Estimated monthly waste: $156.',
    recommendation: 'Set 30-day retention for dev log groups. Implement a tag-based policy to enforce retention on new log groups.',
    remediationStage: 'Backlog',
    remediationProgress: 0,
    comments: [],
  },
  {
    id: 'F-1018',
    title: 'IAM access key older than 90 days detected',
    severity: 'Medium',
    category: 'IAM',
    accountId: 'acc-prod',
    accountName: 'Production',
    environment: 'Production',
    resource: 'AKIA-PROD-DEPLOY-KEY',
    owner: 'Elena Rossi',
    status: 'Open',
    dueDate: '2026-09-14',
    createdAt: '2026-08-07T12:00:00Z',
    description: 'An IAM access key used for CI/CD deployment is older than 90 days and should be rotated.',
    businessRisk: 'Long-lived access keys increase the window of exposure if compromised. Key rotation is a security best practice.',
    businessImpact: 'Security Risk',
    evidence: 'Access key AKIA-PROD-DEPLOY-KEY created 2026-03-10. Last used: 2026-08-19. Age: 162 days.',
    recommendation: 'Rotate the access key. Consider migrating to OIDC-based federation for CI/CD to eliminate long-lived keys entirely.',
    remediationStage: 'Backlog',
    remediationProgress: 0,
    comments: [],
  },
  {
    id: 'F-1019',
    title: 'S3 bucket lacks server-side encryption with KMS',
    severity: 'Medium',
    category: 'S3',
    accountId: 'acc-dev',
    accountName: 'Development',
    environment: 'Development',
    resource: 's3-dev-application-logs',
    owner: 'Marcus Webb',
    status: 'Open',
    dueDate: '2026-09-22',
    createdAt: '2026-08-04T09:00:00Z',
    description: 'An S3 bucket containing application logs does not use KMS-managed server-side encryption.',
    businessRisk: 'Without KMS encryption, data at rest relies on S3 default encryption which may not meet compliance requirements for audit log protection.',
    businessImpact: 'Compliance Risk',
    evidence: 'Bucket s3-dev-application-logs: SSE=SSE-S3 (AES-256), no KMS encryption. Bucket contains 45 GB of application logs.',
    recommendation: 'Enable SSE-KMS with a customer-managed key. Update bucket policy to require KMS encryption for all new objects.',
    remediationStage: 'Backlog',
    remediationProgress: 0,
    comments: [],
  },
  {
    id: 'F-1020',
    title: 'EKS cluster missing recommended managed add-on',
    severity: 'Medium',
    category: 'EKS',
    accountId: 'acc-test',
    accountName: 'Test',
    environment: 'Test',
    resource: 'eks-test-main',
    owner: 'Marcus Webb',
    status: 'Open',
    dueDate: '2026-09-30',
    createdAt: '2026-08-02T11:00:00Z',
    description: 'The test EKS cluster is missing the AWS Load Balancer Controller add-on, affecting ingress and service functionality.',
    businessRisk: 'Without the AWS Load Balancer Controller, ingress and type=LoadBalancer services do not provision ALBs correctly, affecting application routing.',
    businessImpact: 'Operational Risk',
    evidence: 'EKS add-ons for eks-test-main: vpc-cni (installed), kube-proxy (installed), coredns (installed). aws-load-balancer-controller: not installed.',
    recommendation: 'Install the AWS Load Balancer Controller as a managed EKS add-on. Verify IAM role permissions for the controller.',
    remediationStage: 'Backlog',
    remediationProgress: 0,
    comments: [],
  },
  {
    id: 'F-1021',
    title: 'Development VPC lacks flow logs',
    severity: 'Medium',
    category: 'Networking',
    accountId: 'acc-dev',
    accountName: 'Development',
    environment: 'Development',
    resource: 'vpc-dev-main',
    owner: 'Marcus Webb',
    status: 'Open',
    dueDate: '2026-10-01',
    createdAt: '2026-08-01T13:00:00Z',
    description: 'The development VPC does not have flow logs enabled, limiting network debugging capability.',
    businessRisk: 'Without flow logs, network issues in the development environment are harder to diagnose, slowing down development velocity.',
    businessImpact: 'Operational Risk',
    evidence: 'VPC vpc-dev-main: 0 flow log configurations. VPC has 4 subnets and hosts 12 EC2 instances.',
    recommendation: 'Enable VPC Flow Logs to CloudWatch Logs with 30-day retention for the development VPC.',
    remediationStage: 'Backlog',
    remediationProgress: 0,
    comments: [],
  },
  {
    id: 'F-1022',
    title: 'RDS instance lacks multi-AZ deployment',
    severity: 'Medium',
    category: 'Database',
    accountId: 'acc-dev',
    accountName: 'Development',
    environment: 'Development',
    resource: 'db-dev-users-01',
    owner: 'Sarah Chen',
    status: 'Open',
    dueDate: '2026-09-28',
    createdAt: '2026-08-03T10:00:00Z',
    description: 'A development RDS instance is running in single-AZ mode, reducing availability.',
    businessRisk: 'Single-AZ databases have no automatic failover and will experience downtime during AZ outages or maintenance.',
    businessImpact: 'Availability Risk',
    evidence: 'RDS db-dev-users-01: MultiAZ=false, AZ=us-east-1a. Instance class: db.t3.medium. No read replica configured.',
    recommendation: 'Enable Multi-AZ for the RDS instance. For dev environments, consider if the availability tradeoff justifies the cost.',
    remediationStage: 'Backlog',
    remediationProgress: 0,
    comments: [],
  },
  {
    id: 'F-1023',
    title: 'EC2 instance running with outdated instance type',
    severity: 'Medium',
    category: 'Compute',
    accountId: 'acc-dev',
    accountName: 'Development',
    environment: 'Development',
    resource: 'i-dev-build-agent-03',
    owner: 'Marcus Webb',
    status: 'Open',
    dueDate: '2026-10-05',
    createdAt: '2026-07-30T09:00:00Z',
    description: 'An EC2 build agent is running on a previous-generation instance type (m4.large) with suboptimal price-performance.',
    businessRisk: 'Older instance types cost more and perform less than current generations, leading to unnecessary spend.',
    businessImpact: 'Financial Risk',
    evidence: 'Instance i-dev-build-agent-03: type=m4.large, vCPUs=2, RAM=8GB. Equivalent m6i.large: 15% cheaper, 20% better performance.',
    recommendation: 'Migrate to m6i.large or m7i.large. Use EC2 Fleet or a blue-green replacement to minimize downtime.',
    remediationStage: 'Backlog',
    remediationProgress: 0,
    comments: [],
  },
  {
    id: 'F-1024',
    title: 'Lambda function has no dead-letter queue configured',
    severity: 'Medium',
    category: 'Compute',
    accountId: 'acc-prod',
    accountName: 'Production',
    environment: 'Production',
    resource: 'prod-order-processor',
    owner: 'Sarah Chen',
    status: 'Open',
    dueDate: '2026-09-19',
    createdAt: '2026-08-05T14:00:00Z',
    description: 'A production Lambda function processing orders has no dead-letter queue, meaning failed events are silently lost.',
    businessRisk: 'Failed order processing events are lost without a DLQ, leading to silent data loss and customer order failures.',
    businessImpact: 'Data Risk',
    evidence: 'Lambda prod-order-processor: DeadLetterConfig=null. Invocation errors in last 7 days: 23. Failed events: unrecoverable.',
    recommendation: 'Configure an SQS dead-letter queue. Add CloudWatch alarms on DLQ depth and Lambda error rate.',
    remediationStage: 'Backlog',
    remediationProgress: 0,
    comments: [],
  },
  {
    id: 'F-1025',
    title: 'S3 bucket lacks versioning for data protection',
    severity: 'Medium',
    category: 'S3',
    accountId: 'acc-test',
    accountName: 'Test',
    environment: 'Test',
    resource: 's3-test-artifacts',
    owner: 'Marcus Webb',
    status: 'Open',
    dueDate: '2026-10-10',
    createdAt: '2026-07-28T10:00:00Z',
    description: 'An S3 bucket storing test artifacts does not have versioning enabled, preventing recovery from accidental overwrites.',
    businessRisk: 'Without versioning, accidental overwrites or deletes are irreversible, potentially losing test artifacts and reports.',
    businessImpact: 'Operational Risk',
    evidence: 'Bucket s3-test-artifacts: Versioning=Suspended. MFA Delete=disabled. Bucket contains 1,240 test report objects.',
    recommendation: 'Enable versioning on the bucket. Consider enabling MFA delete for additional protection of critical artifacts.',
    remediationStage: 'Backlog',
    remediationProgress: 0,
    comments: [],
  },
  {
    id: 'F-1026',
    title: 'IAM password policy does not meet complexity requirements',
    severity: 'Medium',
    category: 'IAM',
    accountId: 'acc-dev',
    accountName: 'Development',
    environment: 'Development',
    resource: 'IAM Password Policy',
    owner: 'Elena Rossi',
    status: 'Open',
    dueDate: '2026-09-21',
    createdAt: '2026-08-04T11:00:00Z',
    description: 'The IAM password policy for the development account does not enforce minimum length or complexity requirements.',
    businessRisk: 'Weak password policies increase the risk of credential compromise through brute-force or dictionary attacks.',
    businessImpact: 'Security Risk',
    evidence: 'Password policy: MinimumLength=8, RequireSymbols=false, RequireNumbers=false, MaxAge=0 (no rotation).',
    recommendation: 'Update the password policy: minimum 14 characters, require uppercase, lowercase, numbers, symbols, and 90-day rotation.',
    remediationStage: 'Backlog',
    remediationProgress: 0,
    comments: [],
  },
  {
    id: 'F-1027',
    title: 'CloudWatch alarm has no notification action configured',
    severity: 'Medium',
    category: 'Observability',
    accountId: 'acc-prod',
    accountName: 'Production',
    environment: 'Production',
    resource: 'CW-Alarm-Prod-CPU-High',
    owner: 'Sarah Chen',
    status: 'Open',
    dueDate: '2026-09-24',
    createdAt: '2026-08-06T10:00:00Z',
    description: 'A CloudWatch alarm monitoring production CPU utilization has no SNS notification action, so alerts are never sent.',
    businessRisk: 'Critical alarms without notification actions are effectively silent, meaning the team will not be alerted to production issues.',
    businessImpact: 'Availability Risk',
    evidence: 'Alarm CW-Alarm-Prod-CPU-High: Threshold=80%, Period=5min. AlarmActions=[], OKActions=[]. Triggered 3 times in last 30 days.',
    recommendation: 'Attach an SNS topic with email and Slack/PagerDuty subscriptions to the alarm actions.',
    remediationStage: 'Backlog',
    remediationProgress: 0,
    comments: [],
  },
  {
    id: 'F-1028',
    title: 'EKS cluster has no network policies enforced',
    severity: 'Medium',
    category: 'EKS',
    accountId: 'acc-dev',
    accountName: 'Development',
    environment: 'Development',
    resource: 'eks-dev-main',
    owner: 'Marcus Webb',
    status: 'Open',
    dueDate: '2026-10-15',
    createdAt: '2026-07-29T09:00:00Z',
    description: 'The development EKS cluster has no network policies, allowing unrestricted pod-to-pod communication.',
    businessRisk: 'Without network policies, a compromised pod can access all other pods in the cluster, increasing lateral movement risk.',
    businessImpact: 'Security Risk',
    evidence: 'EKS eks-dev-main: Calico/Cilium not installed. 0 NetworkPolicy resources across all namespaces. 67 pods with unrestricted access.',
    recommendation: 'Install a CNI plugin supporting network policies (Calico or Cilium). Start with a default-deny policy and add allow rules per service.',
    remediationStage: 'Backlog',
    remediationProgress: 0,
    comments: [],
  },
  {
    id: 'F-1029',
    title: 'RDS instance lacks automated minor version upgrade',
    severity: 'Medium',
    category: 'Database',
    accountId: 'acc-test',
    accountName: 'Test',
    environment: 'Test',
    resource: 'db-test-config-01',
    owner: 'Sarah Chen',
    status: 'Open',
    dueDate: '2026-10-12',
    createdAt: '2026-07-27T11:00:00Z',
    description: 'A test RDS instance has auto minor version upgrade disabled, meaning security patches are not automatically applied.',
    businessRisk: 'Missing database patches can leave the instance vulnerable to known CVEs that have available fixes.',
    businessImpact: 'Security Risk',
    evidence: 'RDS db-test-config-01: AutoMinorVersionUpgrade=false. Current engine version: 15.3. Available: 15.4 (security patch).',
    recommendation: 'Enable auto minor version upgrade. Schedule upgrades during the defined maintenance window.',
    remediationStage: 'Backlog',
    remediationProgress: 0,
    comments: [],
  },
  {
    id: 'F-1030',
    title: 'API Gateway stage has no access logging enabled',
    severity: 'Medium',
    category: 'Observability',
    accountId: 'acc-prod',
    accountName: 'Production',
    environment: 'Production',
    resource: 'api-prod-orders / prod stage',
    owner: 'Sarah Chen',
    status: 'Open',
    dueDate: '2026-09-29',
    createdAt: '2026-07-31T13:00:00Z',
    description: 'A production API Gateway stage does not have access logging enabled, preventing API request auditing.',
    businessRisk: 'Without access logs, API abuse, errors, and security events cannot be investigated.',
    businessImpact: 'Compliance Risk',
    evidence: 'API Gateway api-prod-orders, stage "prod": accessLogSettings=null. Stage receives ~2M requests/day.',
    recommendation: 'Enable access logging to CloudWatch Logs with a JSON format. Set 90-day retention.',
    remediationStage: 'Backlog',
    remediationProgress: 0,
    comments: [],
  },
  {
    id: 'F-1031',
    title: 'EC2 security group allows all outbound traffic',
    severity: 'Medium',
    category: 'Security',
    accountId: 'acc-dev',
    accountName: 'Development',
    environment: 'Development',
    resource: 'sg-dev-default',
    owner: 'Elena Rossi',
    status: 'Open',
    dueDate: '2026-10-08',
    createdAt: '2026-07-26T10:00:00Z',
    description: 'A security group allows unrestricted outbound traffic to 0.0.0.0/0 on all ports.',
    businessRisk: 'Unrestricted egress allows compromised instances to communicate with any external service, enabling data exfiltration.',
    businessImpact: 'Security Risk',
    evidence: 'SG sg-dev-default: outbound rule 0.0.0.0/0 all ports. SG attached to 8 EC2 instances.',
    recommendation: 'Restrict outbound traffic to required destinations and ports. Use VPC endpoints for AWS service access.',
    remediationStage: 'Backlog',
    remediationProgress: 0,
    comments: [],
  },
  {
    id: 'F-1032',
    title: 'DynamoDB table lacks point-in-time recovery',
    severity: 'Medium',
    category: 'Database',
    accountId: 'acc-prod',
    accountName: 'Production',
    environment: 'Production',
    resource: 'prod-sessions-table',
    owner: 'Sarah Chen',
    status: 'Open',
    dueDate: '2026-09-27',
    createdAt: '2026-07-25T09:00:00Z',
    description: 'A production DynamoDB table does not have point-in-time recovery (PITR) enabled.',
    businessRisk: 'Without PITR, accidental deletes or writes cannot be rolled back, risking data loss for the sessions table.',
    businessImpact: 'Data Risk',
    evidence: 'DynamoDB prod-sessions-table: PointInTimeRecoverySpecification=disabled. Table size: 12 GB. Item count: 4.2M.',
    recommendation: 'Enable point-in-time recovery on the table. PITR provides continuous backups for the last 35 days.',
    remediationStage: 'Backlog',
    remediationProgress: 0,
    comments: [],
  },

  // Low (8)
  {
    id: 'F-1033',
    title: 'S3 bucket lacks lifecycle policy for cost optimization',
    severity: 'Low',
    category: 'S3',
    accountId: 'acc-dev',
    accountName: 'Development',
    environment: 'Development',
    resource: 's3-dev-build-logs',
    owner: 'Marcus Webb',
    status: 'Open',
    dueDate: '2026-10-20',
    createdAt: '2026-07-24T10:00:00Z',
    description: 'An S3 bucket containing build logs has no lifecycle policy, keeping all objects in standard storage indefinitely.',
    businessRisk: 'Without lifecycle policies, storage costs grow unnecessarily as old logs remain in standard storage.',
    businessImpact: 'Financial Risk',
    evidence: 'Bucket s3-dev-build-logs: 0 lifecycle rules. Object count: 89,000. Storage: 124 GB. No transition to Glacier.',
    recommendation: 'Add a lifecycle policy: transition to Glacier after 60 days, expire after 180 days.',
    remediationStage: 'Backlog',
    remediationProgress: 0,
    comments: [],
  },
  {
    id: 'F-1034',
    title: 'IAM user has no MFA device configured',
    severity: 'Low',
    category: 'IAM',
    accountId: 'acc-test',
    accountName: 'Test',
    environment: 'Test',
    resource: 'test-ci-user',
    owner: 'Elena Rossi',
    status: 'Open',
    dueDate: '2026-10-25',
    createdAt: '2026-07-23T11:00:00Z',
    description: 'An IAM user in the test account has no MFA device enrolled.',
    businessRisk: 'Accounts without MFA are more susceptible to credential compromise.',
    businessImpact: 'Security Risk',
    evidence: 'IAM user test-ci-user: MFADevices=[], ConsoleAccess=true, LastLogin=2026-08-15.',
    recommendation: 'Enroll a virtual MFA device for the user. Enforce MFA via IAM policy conditions.',
    remediationStage: 'Backlog',
    remediationProgress: 0,
    comments: [],
  },
  {
    id: 'F-1035',
    title: 'EKS cluster has no resource limits on default namespace',
    severity: 'Low',
    category: 'EKS',
    accountId: 'acc-test',
    accountName: 'Test',
    environment: 'Test',
    resource: 'eks-test-main / default namespace',
    owner: 'Marcus Webb',
    status: 'Open',
    dueDate: '2026-10-30',
    createdAt: '2026-07-22T09:00:00Z',
    description: 'The default namespace in the test EKS cluster has no ResourceQuota, allowing unbounded resource consumption.',
    businessRisk: 'Without ResourceQuotas, any pod in the default namespace can consume unlimited cluster resources.',
    businessImpact: 'Operational Risk',
    evidence: 'Namespace default: ResourceQuota=[], LimitRange=[]. 14 pods running in default namespace.',
    recommendation: 'Apply a ResourceQuota and LimitRange to the default namespace. Move workloads to dedicated namespaces.',
    remediationStage: 'Backlog',
    remediationProgress: 0,
    comments: [],
  },
  {
    id: 'F-1036',
    title: 'CloudWatch dashboard missing for test environment',
    severity: 'Low',
    category: 'Observability',
    accountId: 'acc-test',
    accountName: 'Test',
    environment: 'Test',
    resource: 'CloudWatch Dashboards',
    owner: 'Marcus Webb',
    status: 'Open',
    dueDate: '2026-11-05',
    createdAt: '2026-07-21T10:00:00Z',
    description: 'The test environment has no CloudWatch dashboards, making it difficult to visualize environment health.',
    businessRisk: 'Without dashboards, monitoring the test environment requires manual log inspection, reducing efficiency.',
    businessImpact: 'Operational Risk',
    evidence: 'Account acc-test: 0 CloudWatch dashboards. 3 EC2 instances, 2 RDS instances, 1 EKS cluster with no visualization.',
    recommendation: 'Create dashboards for key resources: EKS cluster health, RDS metrics, EC2 utilization, and alarm status.',
    remediationStage: 'Backlog',
    remediationProgress: 0,
    comments: [],
  },
  {
    id: 'F-1037',
    title: 'S3 bucket inventory configuration not enabled',
    severity: 'Low',
    category: 'S3',
    accountId: 'acc-prod',
    accountName: 'Production',
    environment: 'Production',
    resource: 's3-prod-data-lake',
    owner: 'Sarah Chen',
    status: 'Open',
    dueDate: '2026-11-10',
    createdAt: '2026-07-20T11:00:00Z',
    description: 'A large S3 data lake bucket does not have inventory configuration enabled.',
    businessRisk: 'Without inventory, tracking objects in a large bucket is expensive and slow, complicating audits and lifecycle management.',
    businessImpact: 'Operational Risk',
    evidence: 'Bucket s3-prod-data-lake: inventoryConfig=null. Object count: ~12M. Storage: 8.4 TB.',
    recommendation: 'Enable S3 Inventory with daily CSV reports to a destination bucket. Use for lifecycle and compliance auditing.',
    remediationStage: 'Backlog',
    remediationProgress: 0,
    comments: [],
  },
  {
    id: 'F-1038',
    title: 'EC2 instance has no termination protection',
    severity: 'Low',
    category: 'Compute',
    accountId: 'acc-prod',
    accountName: 'Production',
    environment: 'Production',
    resource: 'i-prod-bastion-01',
    owner: 'Marcus Webb',
    status: 'Open',
    dueDate: '2026-11-01',
    createdAt: '2026-07-19T09:00:00Z',
    description: 'A production bastion host does not have termination protection enabled.',
    businessRisk: 'Without termination protection, the bastion host can be accidentally terminated, cutting off administrative access.',
    businessImpact: 'Operational Risk',
    evidence: 'Instance i-prod-bastion-01: DisableApiTermination=false. Instance is the sole bastion for SSH/SSM access to prod VPC.',
    recommendation: 'Enable termination protection on the bastion host. Add a CloudWatch alarm for instance termination events.',
    remediationStage: 'Backlog',
    remediationProgress: 0,
    comments: [],
  },
  {
    id: 'F-1039',
    title: 'IAM policy contains unused permissions',
    severity: 'Low',
    category: 'IAM',
    accountId: 'acc-prod',
    accountName: 'Production',
    environment: 'Production',
    resource: 'policy-prod-app-s3-access',
    owner: 'Elena Rossi',
    status: 'Open',
    dueDate: '2026-11-15',
    createdAt: '2026-07-18T10:00:00Z',
    description: 'An IAM policy grants S3 permissions to 15 buckets, but the application only accesses 3.',
    businessRisk: 'Overly broad S3 access increases the impact of credential compromise.',
    businessImpact: 'Security Risk',
    evidence: 'Policy policy-prod-app-s3-access: grants ListBucket on 15 buckets. Access Analyzer shows access to only 3 buckets in last 90 days.',
    recommendation: 'Reduce the policy to only the 3 buckets the application accesses. Use Access Analyzer data to right-size.',
    remediationStage: 'Backlog',
    remediationProgress: 0,
    comments: [],
  },
  {
    id: 'F-1040',
    title: 'EKS cluster lacks cluster-autoscaler logging',
    severity: 'Low',
    category: 'EKS',
    accountId: 'acc-test',
    accountName: 'Test',
    environment: 'Test',
    resource: 'eks-test-main / cluster-autoscaler',
    owner: 'Marcus Webb',
    status: 'Open',
    dueDate: '2026-11-20',
    createdAt: '2026-07-17T11:00:00Z',
    description: 'The cluster-autoscaler deployment in the test EKS cluster has verbose logging disabled.',
    businessRisk: 'Without autoscaler logs, diagnosing scaling issues requires manual investigation.',
    businessImpact: 'Operational Risk',
    evidence: 'Deployment cluster-autoscaler in kube-system: log level=1 (info). v=4 not enabled. Recent scaling events: 7 in last week.',
    recommendation: 'Increase log verbosity to v=4 for the cluster-autoscaler. Ship logs to CloudWatch for analysis.',
    remediationStage: 'Backlog',
    remediationProgress: 0,
    comments: [],
  },
];

// Assessments
const eksControls = [
  { controlId: 'EKS-001', name: 'Kubernetes version supported', result: 'Pass' as const, severity: null, description: 'Verifies the EKS control plane runs a supported Kubernetes version.', whyItMatters: 'Unsupported versions do not receive security patches and risk compatibility issues.', evidence: 'Cluster version 1.29. Supported versions: 1.27-1.31.', recommendation: 'Maintain upgrade cadence to stay within supported versions.', findingId: undefined },
  { controlId: 'EKS-002', name: 'EKS add-ons aligned', result: 'Fail' as const, severity: 'High' as const, description: 'Verifies EKS add-on versions are consistent across environments.', whyItMatters: 'Inconsistent add-ons cause environment drift and deployment risk.', evidence: 'vpc-cni version differs between prod (v1.12.0) and dev (v1.11.3).', recommendation: 'Standardize add-on versions via GitOps.', findingId: 'F-1005' },
  { controlId: 'EKS-003', name: 'Nodes healthy', result: 'Pass' as const, severity: null, description: 'Checks all EKS nodes are in Ready state.', whyItMatters: 'NotReady nodes reduce cluster capacity and can cause scheduling failures.', evidence: 'All 12 nodes in Ready state. 0 NotReady nodes.', recommendation: 'No action required.', findingId: undefined },
  { controlId: 'EKS-004', name: 'Pending pods', result: 'Fail' as const, severity: 'Medium' as const, description: 'Checks for pods stuck in Pending state.', whyItMatters: 'Pending pods indicate resource constraints or scheduling issues.', evidence: '3 pods in Pending state in dev cluster due to insufficient CPU.', recommendation: 'Add resource requests or scale the node group.', findingId: 'F-1016' },
  { controlId: 'EKS-005', name: 'Karpenter healthy', result: 'Pass' as const, severity: null, description: 'Verifies Karpenter autoscaler is running and healthy.', whyItMatters: 'Karpenter manages node provisioning; unhealthy autoscaler causes scaling failures.', evidence: 'Karpenter v0.34.0 running, 3 nodes provisioned, 0 errors.', recommendation: 'No action required.', findingId: undefined },
  { controlId: 'EKS-006', name: 'Resource requests configured', result: 'Warning' as const, severity: 'Medium' as const, description: 'Checks that deployments have CPU and memory requests defined.', whyItMatters: 'Without requests, the scheduler cannot make informed placement decisions.', evidence: '23 of 67 deployments have no resource requests.', recommendation: 'Define resource requests for all workloads.', findingId: 'F-1016' },
  { controlId: 'EKS-007', name: 'Monitoring enabled', result: 'Pass' as const, severity: null, description: 'Verifies Container Insights or equivalent monitoring is enabled.', whyItMatters: 'Monitoring is essential for detecting and diagnosing cluster issues.', evidence: 'CloudWatch Container Insights enabled on all 3 clusters.', recommendation: 'No action required.', findingId: undefined },
];

function makeAssessment(
  id: string,
  name: string,
  accountId: string,
  accountName: string,
  environment: any,
  category: any,
  score: number,
  findingsCount: number,
  startedAt: string,
  completedAt: string,
  status: any,
  controls: any[] = eksControls
): Assessment {
  return { id, name, accountId, accountName, environment, category, score, findingsCount, startedAt, completedAt, status, controls };
}

export const assessments: Assessment[] = [
  makeAssessment('A-001', 'EKS Reliability Assessment', 'acc-prod', 'Production', 'Production', 'EKS', 84, 3, '2026-08-18T09:00:00Z', '2026-08-18T09:30:00Z', 'Completed'),
  makeAssessment('A-002', 'Security Posture Assessment', 'acc-prod', 'Production', 'Production', 'Security', 91, 4, '2026-08-17T10:00:00Z', '2026-08-17T10:45:00Z', 'Completed'),
  makeAssessment('A-003', 'IAM Privilege Review', 'acc-prod', 'Production', 'Production', 'IAM', 82, 3, '2026-08-16T11:00:00Z', '2026-08-16T11:30:00Z', 'Completed'),
  makeAssessment('A-004', 'S3 Configuration Audit', 'acc-prod', 'Production', 'Production', 'S3', 88, 2, '2026-08-15T09:00:00Z', '2026-08-15T09:20:00Z', 'Completed'),
  makeAssessment('A-005', 'Networking Flow Log Audit', 'acc-prod', 'Production', 'Production', 'Networking', 76, 2, '2026-08-14T13:00:00Z', '2026-08-14T13:30:00Z', 'Completed'),
  makeAssessment('A-006', 'Observability Coverage Assessment', 'acc-prod', 'Production', 'Production', 'Observability', 73, 3, '2026-08-13T10:00:00Z', '2026-08-13T10:40:00Z', 'Completed'),
  makeAssessment('A-007', 'Backup & DR Readiness Assessment', 'acc-prod', 'Production', 'Production', 'Backup', 69, 2, '2026-08-12T09:00:00Z', '2026-08-12T09:30:00Z', 'Completed'),
  makeAssessment('A-008', 'Governance & Tagging Audit', 'acc-prod', 'Production', 'Production', 'Governance', 78, 1, '2026-08-11T11:00:00Z', '2026-08-11T11:20:00Z', 'Completed'),
  makeAssessment('A-009', 'EKS Reliability Assessment', 'acc-dev', 'Development', 'Development', 'EKS', 72, 4, '2026-08-17T14:00:00Z', '2026-08-17T14:30:00Z', 'Completed'),
  makeAssessment('A-010', 'Security Posture Assessment', 'acc-dev', 'Development', 'Development', 'Security', 79, 3, '2026-08-16T10:00:00Z', '2026-08-16T10:30:00Z', 'Completed'),
  makeAssessment('A-011', 'IAM Privilege Review', 'acc-dev', 'Development', 'Development', 'IAM', 74, 2, '2026-08-15T11:00:00Z', '2026-08-15T11:20:00Z', 'Completed'),
  makeAssessment('A-012', 'S3 Configuration Audit', 'acc-dev', 'Development', 'Development', 'S3', 80, 2, '2026-08-14T09:00:00Z', '2026-08-14T09:15:00Z', 'Completed'),
  makeAssessment('A-013', 'EKS Reliability Assessment', 'acc-test', 'Test', 'Test', 'EKS', 85, 2, '2026-08-16T11:00:00Z', '2026-08-16T11:30:00Z', 'Completed'),
  makeAssessment('A-014', 'Backup & DR Readiness Assessment', 'acc-dev', 'Development', 'Development', 'Backup', 71, 1, '2026-08-13T09:00:00Z', '2026-08-13T09:20:00Z', 'Completed'),
  makeAssessment('A-015', 'Governance & Tagging Audit', 'acc-dev', 'Development', 'Development', 'Governance', 75, 1, '2026-08-12T11:00:00Z', '2026-08-12T11:15:00Z', 'Completed'),
  makeAssessment('A-016', 'Compute Optimization Assessment', 'acc-prod', 'Production', 'Production', 'Compute', 83, 2, '2026-08-19T08:00:00Z', '', 'Running'),
  makeAssessment('A-017', 'Database Reliability Assessment', 'acc-prod', 'Production', 'Production', 'Database', 0, 0, '2026-08-20T09:00:00Z', '', 'Scheduled'),
];

export const automations: Automation[] = [
  { id: 'AUT-001', name: 'AWS Security Group Scanner', description: 'Scans all security groups for unrestricted SSH, RDP, and overly permissive rules across connected accounts.', category: 'Security', status: 'Active', schedule: 'Daily 06:00 UTC', lastRun: '2026-08-19T06:00:00Z', findingsGenerated: 14 },
  { id: 'AUT-002', name: 'EKS Health Scanner', description: 'Checks EKS clusters for supported versions, add-on alignment, node health, and resource request compliance.', category: 'EKS', status: 'Planned', schedule: 'Daily 07:00 UTC', findingsGenerated: 0 },
  { id: 'AUT-003', name: 'S3 Configuration Scanner', description: 'Audits S3 buckets for public access, encryption, versioning, and lifecycle policies.', category: 'S3', status: 'Planned', schedule: 'Weekly Sunday', findingsGenerated: 0 },
  { id: 'AUT-004', name: 'IAM Permission Analyzer', description: 'Analyzes IAM roles and policies for least-privilege violations, unused roles, and key age.', category: 'IAM', status: 'Planned', schedule: 'Weekly Monday', findingsGenerated: 0 },
  { id: 'AUT-005', name: 'CloudWatch Retention Scanner', description: 'Identifies CloudWatch log groups without retention policies and excessive storage.', category: 'Observability', status: 'Planned', schedule: 'Weekly Monday', findingsGenerated: 0 },
  { id: 'AUT-006', name: 'AWS Resource Inventory', description: 'Inventories all resources across connected accounts and validates required tagging compliance.', category: 'Governance', status: 'Planned', schedule: 'Daily 05:00 UTC', findingsGenerated: 0 },
];

export const automationExecutions: AutomationExecution[] = [
  { id: 'EX-001', automationId: 'AUT-001', automationName: 'AWS Security Group Scanner', status: 'Completed', startedAt: '2026-08-19T06:00:00Z', completedAt: '2026-08-19T06:04:32Z', findingsGenerated: 2 },
  { id: 'EX-002', automationId: 'AUT-001', automationName: 'AWS Security Group Scanner', status: 'Completed', startedAt: '2026-08-18T06:00:00Z', completedAt: '2026-08-18T06:03:51Z', findingsGenerated: 1 },
  { id: 'EX-003', automationId: 'AUT-001', automationName: 'AWS Security Group Scanner', status: 'Completed', startedAt: '2026-08-17T06:00:00Z', completedAt: '2026-08-17T06:04:10Z', findingsGenerated: 0 },
];

export const remediations: Remediation[] = findings
  .filter((f) => f.remediationStage)
  .map((f) => ({
    findingId: f.id,
    findingTitle: f.title,
    owner: f.owner,
    priority: f.severity === 'Critical' ? 'P1' : f.severity === 'High' ? 'P2' : f.severity === 'Medium' ? 'P3' : 'P4',
    dueDate: f.dueDate,
    stage: f.remediationStage!,
    progress: f.remediationProgress ?? 0,
  }));

export const reports: Report[] = [
  {
    id: 'R-001',
    title: 'Monthly AWS Platform Health',
    period: 'August 2026',
    generatedAt: '2026-08-19T08:00:00Z',
    healthScore: 82,
    previousHealthScore: 76,
    findingsResolved: 31,
    highPriorityRemaining: 12,
    automationsIdentified: 5,
    summary: 'Platform health improved from 76 to 82. 31 findings resolved. 12 high-priority findings remain. 5 operational workflows identified for automation.',
  },
  {
    id: 'R-002',
    title: 'Monthly AWS Platform Health',
    period: 'July 2026',
    generatedAt: '2026-07-31T08:00:00Z',
    healthScore: 76,
    previousHealthScore: 75,
    findingsResolved: 24,
    highPriorityRemaining: 18,
    automationsIdentified: 3,
    summary: 'Platform health improved from 75 to 76. 24 findings resolved. 18 high-priority findings remain. 3 operational workflows identified for automation.',
  },
  {
    id: 'R-003',
    title: 'Monthly AWS Platform Health',
    period: 'June 2026',
    generatedAt: '2026-06-30T08:00:00Z',
    healthScore: 75,
    previousHealthScore: 73,
    findingsResolved: 19,
    highPriorityRemaining: 22,
    automationsIdentified: 2,
    summary: 'Platform health improved from 73 to 75. 19 findings resolved. 22 high-priority findings remain.',
  },
];

export const auditLog: AuditLogEntry[] = [
  { id: 'AL-001', user: 'Pawan Kumar', action: 'changed status', resource: 'F-1024', timestamp: '2026-08-19T09:15:00Z', previousValue: 'Open', newValue: 'In Progress' },
  { id: 'AL-002', user: 'Sarah Chen', action: 'assigned', resource: 'F-1001', timestamp: '2026-08-19T08:30:00Z', previousValue: 'Unassigned', newValue: 'Sarah Chen' },
  { id: 'AL-003', user: 'Elena Rossi', action: 'changed severity', resource: 'F-1002', timestamp: '2026-08-18T16:45:00Z', previousValue: 'High', newValue: 'Critical' },
  { id: 'AL-004', user: 'Marcus Webb', action: 'marked resolved', resource: 'F-0992', timestamp: '2026-08-18T14:20:00Z', previousValue: 'In Progress', newValue: 'Resolved' },
  { id: 'AL-005', user: 'Sarah Chen', action: 'added comment', resource: 'F-1001', timestamp: '2026-08-18T11:00:00Z' },
  { id: 'AL-006', user: 'Pawan Kumar', action: 'accepted risk', resource: 'F-0988', timestamp: '2026-08-17T15:30:00Z', previousValue: 'Open', newValue: 'Accepted Risk' },
  { id: 'AL-007', user: 'Elena Rossi', action: 'ran automation', resource: 'AWS Security Group Scanner', timestamp: '2026-08-19T06:00:00Z' },
  { id: 'AL-008', user: 'Sarah Chen', action: 'generated report', resource: 'Monthly AWS Platform Health — August 2026', timestamp: '2026-08-19T08:00:00Z' },
  { id: 'AL-009', user: 'Marcus Webb', action: 'changed status', resource: 'F-1005', timestamp: '2026-08-17T10:15:00Z', previousValue: 'Planned', newValue: 'In Progress' },
  { id: 'AL-010', user: 'Pawan Kumar', action: 'updated settings', resource: 'Notification Settings', timestamp: '2026-08-16T09:00:00Z' },
];

export const notifications: Notification[] = [
  { id: 'N-001', title: '4 critical findings require attention', description: 'Critical findings in Production account need immediate action.', type: 'critical', timestamp: '2026-08-19T09:00:00Z', read: false },
  { id: 'N-002', title: 'EKS assessment completed', description: 'EKS Reliability Assessment for Production completed with score 84/100.', type: 'info', timestamp: '2026-08-18T09:30:00Z', read: false },
  { id: 'N-003', title: 'Finding F-1006 is due in 7 days', description: 'Security group allows unrestricted SSH access — due Sep 15.', type: 'warning', timestamp: '2026-08-19T08:00:00Z', read: false },
  { id: 'N-004', title: '31 findings resolved this month', description: 'Great progress — 31 findings resolved in August.', type: 'success', timestamp: '2026-08-19T07:00:00Z', read: true },
  { id: 'N-005', title: 'Automation completed', description: 'AWS Security Group Scanner generated 2 new findings.', type: 'info', timestamp: '2026-08-19T06:04:00Z', read: true },
];

export const activityEvents: ActivityEvent[] = [
  { id: 'AE-001', type: 'report_generated', description: 'Monthly AWS Platform Health report generated for August 2026', timestamp: '2026-08-19T08:00:00Z', user: 'Sarah Chen' },
  { id: 'AE-002', type: 'finding_assigned', description: 'F-1001 assigned to Sarah Chen', timestamp: '2026-08-19T08:30:00Z', user: 'Pawan Kumar' },
  { id: 'AE-003', type: 'finding_resolved', description: 'F-0992 marked resolved', timestamp: '2026-08-18T14:20:00Z', user: 'Marcus Webb' },
  { id: 'AE-004', type: 'assessment_completed', description: 'Security assessment completed for Production', timestamp: '2026-08-17T10:45:00Z', user: 'System' },
  { id: 'AE-005', type: 'control_failed', description: 'EKS add-ons aligned check failed for Production', timestamp: '2026-08-18T09:25:00Z', user: 'System' },
  { id: 'AE-006', type: 'automation_executed', description: 'AWS Security Group Scanner executed — 2 findings generated', timestamp: '2026-08-19T06:04:00Z', user: 'System' },
  { id: 'AE-007', type: 'finding_created', description: 'F-1004 created: CloudTrail logging disabled in us-west-2', timestamp: '2026-08-15T16:00:00Z', user: 'System' },
  { id: 'AE-008', type: 'assessment_completed', description: 'EKS reliability assessment completed', timestamp: '2026-08-18T09:30:00Z', user: 'System' },
];

export const kpiTrends = {
  criticalFindings: { current: 4, previous: 6, trend: 'down' as const, change: '33%' },
  highFindings: { current: 12, previous: 15, trend: 'down' as const, change: '20%' },
  openFindings: { current: 47, previous: 58, trend: 'down' as const, change: '19%' },
  findingsResolved: { current: 31, previous: 24, trend: 'up' as const, change: '29%' },
  automationCoverage: { current: 62, previous: 55, trend: 'up' as const, change: '13%' },
  platformHealth: { current: 82, previous: 76, trend: 'up' as const, change: '8%' },
};
