import type { Role } from '@/lib/db-types';

export const PERMISSIONS = {
  // Findings
  FINDINGS_READ: 'findings:read',
  FINDINGS_UPDATE: 'findings:update',
  FINDINGS_CREATE: 'findings:create',
  FINDINGS_DELETE: 'findings:delete',
  // Assessments
  ASSESSMENTS_READ: 'assessments:read',
  ASSESSMENTS_CREATE: 'assessments:create',
  ASSESSMENTS_UPDATE: 'assessments:update',
  // Accounts
  ACCOUNTS_READ: 'accounts:read',
  ACCOUNTS_MANAGE: 'accounts:manage',
  // Controls
  CONTROLS_READ: 'controls:read',
  CONTROLS_MANAGE: 'controls:manage',
  // Remediation
  REMEDIATION_READ: 'remediation:read',
  REMEDIATION_MANAGE: 'remediation:manage',
  // Automation
  AUTOMATION_READ: 'automation:read',
  AUTOMATION_MANAGE: 'automation:manage',
  AUTOMATION_EXECUTE: 'automation:execute',
  // Reports
  REPORTS_READ: 'reports:read',
  REPORTS_GENERATE: 'reports:generate',
  // Audit
  AUDIT_READ: 'audit:read',
  // Settings
  SETTINGS_READ: 'settings:read',
  SETTINGS_MANAGE: 'settings:manage',
  // Users
  USERS_READ: 'users:read',
  USERS_MANAGE: 'users:manage',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

const ROLE_PERMISSIONS: Record<Role, Set<Permission>> = {
  SUPER_ADMIN: new Set(Object.values(PERMISSIONS)),
  PLATFORM_ADMIN: new Set<Permission>([
    PERMISSIONS.FINDINGS_READ, PERMISSIONS.FINDINGS_UPDATE, PERMISSIONS.FINDINGS_CREATE,
    PERMISSIONS.ASSESSMENTS_READ, PERMISSIONS.ASSESSMENTS_CREATE, PERMISSIONS.ASSESSMENTS_UPDATE,
    PERMISSIONS.ACCOUNTS_READ, PERMISSIONS.ACCOUNTS_MANAGE,
    PERMISSIONS.CONTROLS_READ,
    PERMISSIONS.REMEDIATION_READ, PERMISSIONS.REMEDIATION_MANAGE,
    PERMISSIONS.AUTOMATION_READ, PERMISSIONS.AUTOMATION_MANAGE, PERMISSIONS.AUTOMATION_EXECUTE,
    PERMISSIONS.REPORTS_READ, PERMISSIONS.REPORTS_GENERATE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.SETTINGS_READ, PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.USERS_READ, PERMISSIONS.USERS_MANAGE,
  ]),
  DEVOPS_ENGINEER: new Set<Permission>([
    PERMISSIONS.FINDINGS_READ, PERMISSIONS.FINDINGS_UPDATE,
    PERMISSIONS.ASSESSMENTS_READ,
    PERMISSIONS.ACCOUNTS_READ,
    PERMISSIONS.CONTROLS_READ,
    PERMISSIONS.REMEDIATION_READ, PERMISSIONS.REMEDIATION_MANAGE,
    PERMISSIONS.AUTOMATION_READ,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.USERS_READ,
  ]),
  SECURITY_ENGINEER: new Set<Permission>([
    PERMISSIONS.FINDINGS_READ, PERMISSIONS.FINDINGS_UPDATE, PERMISSIONS.FINDINGS_CREATE,
    PERMISSIONS.ASSESSMENTS_READ, PERMISSIONS.ASSESSMENTS_CREATE,
    PERMISSIONS.ACCOUNTS_READ,
    PERMISSIONS.CONTROLS_READ, PERMISSIONS.CONTROLS_MANAGE,
    PERMISSIONS.REMEDIATION_READ, PERMISSIONS.REMEDIATION_MANAGE,
    PERMISSIONS.AUTOMATION_READ, PERMISSIONS.AUTOMATION_EXECUTE,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.USERS_READ,
  ]),
  VIEWER: new Set<Permission>([
    PERMISSIONS.FINDINGS_READ,
    PERMISSIONS.ASSESSMENTS_READ,
    PERMISSIONS.ACCOUNTS_READ,
    PERMISSIONS.CONTROLS_READ,
    PERMISSIONS.REMEDIATION_READ,
    PERMISSIONS.AUTOMATION_READ,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.USERS_READ,
  ]),
};

export function hasPermission(role: Role, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role]?.has(permission) ?? false;
}

export function canManageFinding(role: Role, isOwner: boolean): boolean {
  if (role === 'SUPER_ADMIN' || role === 'PLATFORM_ADMIN') return true;
  if (role === 'SECURITY_ENGINEER' || role === 'DEVOPS_ENGINEER') return isOwner;
  return false;
}
